### ISSUE TITLE
Double borders issue

### ISSUE THREAD

**Issue by nWidart** [Maatwebsite/Laravel-Sidebar#2]
There some kind of 'bug' with the borders on the items, which makes it 'blurry':

![screen_shot_2015-02-13_at_7_00_54_pm](https://cloud.githubusercontent.com/assets/882397/6192478/c560fdee-b3b2-11e4-9d86-362bfffa2fee.png)

**Comment by nWidart** [comment]
From what I can see it is cause by the fact that every item is the first element. Since every item is one `ul`.

``` css
.skin-blue .sidebar > .sidebar-menu > li:first-of-type {
border-top: 1px solid #dbdbdb;
}
```
